[
  [
    [
      "字",
      "word",
      null,
      null,
      2
    ],
    [
      null,
      null,
      "Zì",
      "wərd"
    ]
  ],
  [
    [
      "名词",
      [
        "字",
        "词",
        "单词",
        "话",
        "言",
        "言辞",
        "笔墨",
        "约言"
      ],
      [
        [
          "字",
          [
            "word",
            "character",
            "letter",
            "calligraphy",
            "symbol",
            "style of writing"
          ],
          null,
          0.27768996
        ],
        [
          "词",
          [
            "word",
            "term",
            "speech",
            "statement"
          ],
          null,
          0.10874496
        ],
        [
          "单词",
          [
            "word",
            "individual word"
          ],
          null,
          0.083377652
        ],
        [
          "话",
          [
            "words",
            "word",
            "dialect",
            "saying",
            "talk",
            "speech"
          ],
          null,
          0.022440789
        ],
        [
          "言",
          [
            "word",
            "speech",
            "character"
          ],
          null,
          0.0032838131
        ],
        [
          "言辞",
          [
            "words",
            "word",
            "what one says"
          ],
          null,
          0.00014428068
        ],
        [
          "笔墨",
          [
            "pen and ink",
            "words",
            "word",
            "writings"
          ],
          null,
          2.1783124e-05
        ],
        [
          "约言",
          [
            "pledge",
            "promise",
            "word"
          ]
        ]
      ],
      "word",
      1
    ]
  ],
  "en",
  null,
  null,
  [
    [
      "word",
      null,
      [
        [
          "字",
          1000,
          true,
          false
        ],
        [
          "词",
          1000,
          true,
          false
        ],
        [
          "单词",
          1000,
          true,
          false
        ]
      ],
      [
        [
          0,
          4
        ]
      ],
      "word",
      0,
      0
    ]
  ],
  0.93603134,
  null,
  [
    [
      "en"
    ],
    null,
    [
      0.93603134
    ],
    [
      "en"
    ]
  ],
  null,
  null,
  [
    [
      "名词",
      [
        [
          [
            "term",
            "name",
            "expression",
            "designation",
            "locution",
            "vocable",
            "appellation"
          ],
          "m_en_us1307021.001"
        ],
        [
          [
            "remark",
            "comment",
            "observation",
            "statement",
            "utterance",
            "pronouncement"
          ],
          "m_en_us1307021.003"
        ],
        [
          [
            "script",
            "lyrics",
            "libretto"
          ],
          "m_en_us1307021.008"
        ],
        [
          [
            "promise",
            "word of honor",
            "assurance",
            "guarantee",
            "undertaking",
            "pledge",
            "vow",
            "oath",
            "bond",
            "troth"
          ],
          "m_en_us1307021.038"
        ],
        [
          [
            "talk",
            "conversation",
            "chat",
            "tête-à-tête",
            "heart-to-heart",
            "one-to-one",
            "man-to-man",
            "discussion",
            "consultation",
            "confab",
            "powwow",
            "confabulation"
          ],
          ""
        ],
        [
          [
            "news",
            "information",
            "communication",
            "intelligence",
            "message",
            "report",
            "communiqué",
            "dispatch",
            "bulletin",
            "info",
            "dope",
            "tidings"
          ],
          "m_en_us1307021.010"
        ],
        [
          [
            "rumor",
            "hearsay",
            "talk",
            "gossip",
            "the grapevine",
            "the word on the street"
          ],
          "m_en_us1307021.010"
        ],
        [
          [
            "instruction",
            "order",
            "command",
            "signal",
            "prompt",
            "cue",
            "tip-off",
            "go-ahead",
            "thumbs up",
            "green light"
          ],
          "m_en_us1307021.011"
        ],
        [
          [
            "command",
            "order",
            "decree",
            "edict",
            "bidding",
            "will"
          ],
          "m_en_us1307021.011"
        ],
        [
          [
            "motto",
            "watchword",
            "slogan",
            "catchword",
            "buzzword"
          ],
          ""
        ],
        [
          [
            "son",
            "logos"
          ],
          ""
        ],
        [
          [
            "tidings",
            "news",
            "intelligence"
          ],
          ""
        ],
        [
          [
            "book",
            "scripture",
            "bible",
            "word of god",
            "good book"
          ],
          ""
        ],
        [
          [
            "give-and-take",
            "discussion"
          ],
          ""
        ],
        [
          [
            "parole",
            "word of honor"
          ],
          ""
        ],
        [
          [
            "watchword",
            "password",
            "countersign",
            "parole"
          ],
          ""
        ]
      ],
      "word"
    ],
    [
      "动词",
      [
        [
          [
            "phrase",
            "express",
            "put",
            "couch",
            "frame",
            "formulate",
            "style",
            "say",
            "utter"
          ],
          "m_en_us1307021.013"
        ],
        [
          [
            "phrase",
            "formulate",
            "give voice",
            "articulate"
          ],
          ""
        ]
      ],
      "word"
    ]
  ],
  [
    [
      "名词",
      [
        [
          "a single distinct meaningful element of speech or writing, used with others (or sometimes alone) to form a sentence and typically shown with a space on either side when written or printed.",
          "m_en_us1307021.001",
          "He attempted to say a few things, but none of the noises actually turned into words let alone sentences."
        ]
      ],
      "word"
    ],
    [
      "动词",
      [
        [
          "choose and use particular words in order to say or write (something).",
          "m_en_us1307021.013",
          "he words his request in a particularly ironic way"
        ]
      ],
      "word"
    ],
    [
      "惊叹词",
      [
        [
          "used to express agreement.",
          "m_en_us1307021.014",
          "“That Jay is one dangerous character.” “Word.”"
        ]
      ],
      "word"
    ],
    [
      "后缀",
      [
        [
          "denoting a word that may be offensive or have a negative connotation, specified by the word's first letter.",
          "m_en_us1307022.001",
          "the F-word"
        ]
      ],
      "-word"
    ]
  ],
  [
    [
      [
        "a \u003cb\u003eword\u003c/b\u003e of warning",
        null,
        null,
        null,
        3,
        "m_en_gb0959560.003"
      ],
      [
        "If a really big one hits a remote area, it might become news, if \u003cb\u003eword\u003c/b\u003e eventually gets back to the metropolis.",
        null,
        null,
        null,
        3,
        "m_en_us1307021.010"
      ],
      [
        "code \u003cb\u003eword\u003c/b\u003e",
        null,
        null,
        null,
        3,
        "neid_23053"
      ],
      [
        "Members spread the \u003cb\u003eword\u003c/b\u003e by text messages, e-mails and leaflets which are handed out in towns and cities.",
        null,
        null,
        null,
        3,
        "m_en_us1307021.010"
      ],
      [
        "If you accept her word, you are saying that my \u003cb\u003eword\u003c/b\u003e , because I gave it first, is not to be believed.",
        null,
        null,
        null,
        3,
        "m_en_us1307021.006"
      ],
      [
        "Steve's unchanged expression showed that he didn't believe a \u003cb\u003eword\u003c/b\u003e Miles had just spoken.",
        null,
        null,
        null,
        3,
        "m_en_us1307021.005"
      ],
      [
        "Why is everyone falling in love with Bridget when she's let her looks go to pot and appears in \u003cb\u003eword\u003c/b\u003e , deed and fashion air-brained?",
        null,
        null,
        null,
        3,
        "m_en_us1307021.004"
      ],
      [
        "he conforms in \u003cb\u003eword\u003c/b\u003e and deed to the values of a society that he rejects",
        null,
        null,
        null,
        3,
        "m_en_us1307021.004"
      ],
      [
        "He hadn't seen this side of Ron yet, this, for lack of a better \u003cb\u003eword\u003c/b\u003e , bitchy side and he was strangely unsurprised by it.",
        null,
        null,
        null,
        3,
        "m_en_us1307021.001"
      ],
      [
        "it was his \u003cb\u003eword\u003c/b\u003e against hers",
        null,
        null,
        null,
        3,
        "neid_23062"
      ],
      [
        "someone gave me the \u003cb\u003eword\u003c/b\u003e to start playing",
        null,
        null,
        null,
        3,
        "m_en_us1307021.011"
      ],
      [
        "a \u003cb\u003eword\u003c/b\u003e of thanks",
        null,
        null,
        null,
        3,
        "neid_23055"
      ],
      [
        "\u003cb\u003eword\u003c/b\u003e order",
        null,
        null,
        null,
        3,
        "neid_23053"
      ],
      [
        "I assured him that I had none of the above, but my \u003cb\u003eword\u003c/b\u003e was not good enough.",
        null,
        null,
        null,
        3,
        "m_en_us1307021.007"
      ],
      [
        "The people who know me well don't believe a \u003cb\u003eword\u003c/b\u003e of what is written by the media.",
        null,
        null,
        null,
        3,
        "m_en_us1307021.005"
      ],
      [
        "The villains are truly dangerous and the heroes are valiant in \u003cb\u003eword\u003c/b\u003e and deed.",
        null,
        null,
        null,
        3,
        "m_en_us1307021.004"
      ],
      [
        "When the waitress arrives, Beanie's mother remains true to her \u003cb\u003eword\u003c/b\u003e and orders only coffee.",
        null,
        null,
        null,
        3,
        "m_en_us1307021.007"
      ],
      [
        "We can only do our best to hold the administration to its \u003cb\u003eword\u003c/b\u003e .",
        null,
        null,
        null,
        3,
        "m_en_us1307021.007"
      ],
      [
        "By then I had already made a promise to Dundee, and I wasn't going to go back on my \u003cb\u003eword\u003c/b\u003e .",
        null,
        null,
        null,
        3,
        "m_en_us1307021.007"
      ],
      [
        "All I will say is that this movie was true in the basic sense of the \u003cb\u003eword\u003c/b\u003e .",
        null,
        null,
        null,
        3,
        "m_en_us1307021.002"
      ],
      [
        "Some of the contributors here took issue with the meaning of the \u003cb\u003eword\u003c/b\u003e print itself.",
        null,
        null,
        null,
        3,
        "m_en_us1307021.001"
      ],
      [
        "In fact, \u003cb\u003eword\u003c/b\u003e spread so quickly about the club, that people were travelling from all over Bradford to go to the meetings.",
        null,
        null,
        null,
        3,
        "m_en_us1307021.010"
      ],
      [
        "I regard his statements that my \u003cb\u003eword\u003c/b\u003e cannot be believed as offensive, and I would ask him to withdraw and apologise.",
        null,
        null,
        null,
        3,
        "m_en_us1307021.007"
      ],
      [
        "Then, he picked out a piece of paper and unfolded the paper that had the \u003cb\u003eword\u003c/b\u003e , Dianna written on it.",
        null,
        null,
        null,
        3,
        "m_en_us1307021.001"
      ],
      [
        "Kumar has never harmed anyone by thought, \u003cb\u003eword\u003c/b\u003e or deed, as far as I know.",
        null,
        null,
        null,
        3,
        "m_en_us1307021.004"
      ],
      [
        "I realise that this is a retraction of my \u003cb\u003eword\u003c/b\u003e given to the Reverend.",
        null,
        null,
        null,
        3,
        "m_en_us1307021.007"
      ],
      [
        "In her short time in this organized hell, Cassie understood the meaning of the \u003cb\u003eword\u003c/b\u003e alone.",
        null,
        null,
        null,
        3,
        "m_en_us1307021.001"
      ],
      [
        "The crucial distinction between the fifties and sixties lay in \u003cb\u003eword\u003c/b\u003e , not in deed.",
        null,
        null,
        null,
        3,
        "m_en_us1307021.004"
      ],
      [
        "In fact, \u003cb\u003eword\u003c/b\u003e has it that the unbelieving William III even referred petitioners he turned away to his vanquished rivals.",
        null,
        null,
        null,
        3,
        "m_en_us1307021.010"
      ],
      [
        "Not a \u003cb\u003eword\u003c/b\u003e was spoken to explain the missiles raining down.",
        null,
        null,
        null,
        3,
        "m_en_us1307021.005"
      ]
    ]
  ],
  [
    [
      "Word",
      "word processor",
      "word of mouth",
      "word processing",
      "last word",
      "swear word",
      "one word",
      "word order",
      "compound word",
      "word list",
      "new word"
    ]
  ]
]
